// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductSuggestionAPP.DataContexts;

namespace ProductSuggestionAPP.Migrations
{
    [DbContext(typeof(SalesContext))]
    partial class SalesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ProductSuggestionAPP.Models.SALES_DATA", b =>
                {
                    b.Property<int>("SD_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("SD_CUST_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SD_PRODUCT_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SD_PRODUCT_PRICE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SD_PROD_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SD_STORE_ID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SD_ID");

                    b.ToTable("SalesData");
                });
#pragma warning restore 612, 618
        }
    }
}
